

import { SystemState, Agent, Strategy, StrategyType, CollectiveState, AuditLog, LogLevel, EvolutionaryState, EvolutionHistoryPoint, DataSource, DataSourceType, ConsensusSignal, VoteDecision, AIBoardState, AIBoardDirective, AgentType, QuantumAddon, ModelRoute, ModelTaskType, Prediction, BoardEvent, ModelVote, AIBoardModel } from './types';

const XAUUSD_MQL5_CODE = `//+------------------------------------------------------------------+
//|                        XAUUSD_Hybrid_EMA_System.mq5              |
//|                        Generated by VortigenOS                   |
//|                        Strategy: Institutional Hybrid EMA (8/12/100) |
//|                        With HMA, ALMA & Dynamic Confidence Sizing|
//+------------------------------------------------------------------+
#property copyright "VortigenOS AI"
#property link      "https://vortigen.os"
#property version   "3.2"
#property strict
#include <Trade\\Trade.mqh>

// --- INPUT PARAMETERS ---
input double   BaseRiskPercent  = 1.0;          // Base Risk % per trade
input double   MaxLotSize       = 10.0;         // Hard Cap on Lots
input int      MagicNumber      = 888999;       // Magic Number
input int      EMA_Fast         = 8;            // Momentum (Fast)
input int      EMA_Slow         = 12;           // Trend Check (Slow)
input int      EMA_Anchor       = 100;          // Macro Trend Anchor
input int      ATR_Period       = 14;           // Volatility
input double   ATR_Multiplier   = 1.5;          // Dynamic SL Multiplier
input int      HMA_Period       = 55;           // Hull Moving Average
input int      ALMA_Period      = 21;           // Arnaud Legoux MA
input double   ALMA_Sigma       = 6.0;
input double   ALMA_Offset      = 0.85;

// --- HANDLES ---
int hFast, hSlow, hAnchor, hATR, hHMA, hALMA;
CTrade trade;

// --- INITIALIZATION ---
int OnInit() {
   trade.SetExpertMagicNumber(MagicNumber);
   
   hFast   = iMA(_Symbol, PERIOD_H1, EMA_Fast, 0, MODE_EMA, PRICE_CLOSE);
   hSlow   = iMA(_Symbol, PERIOD_H1, EMA_Slow, 0, MODE_EMA, PRICE_CLOSE);
   hAnchor = iMA(_Symbol, PERIOD_H1, EMA_Anchor, 0, MODE_EMA, PRICE_CLOSE);
   hATR    = iATR(_Symbol, PERIOD_H1, ATR_Period);
   hHMA    = iCustom(_Symbol, PERIOD_H1, "Custom\\HMA", HMA_Period);
   hALMA   = iCustom(_Symbol, PERIOD_H1, "Custom\\ALMA", ALMA_Period, ALMA_Sigma, ALMA_Offset);
   
   if(hFast == INVALID_HANDLE || hSlow == INVALID_HANDLE || hAnchor == INVALID_HANDLE || hHMA == INVALID_HANDLE) {
      Print("Error initializing indicators");
      return(INIT_FAILED);
   }
   return(INIT_SUCCEEDED);
}

// --- UTILS ---
bool IsNewCandle() {
   static datetime lastTime = 0;
   datetime currentTime = iTime(_Symbol, PERIOD_H1, 0);
   if(lastTime != currentTime) { lastTime = currentTime; return true; }
   return false;
}

double CalculateConfidence(double fast, double slow, double anchor, double hma, double alma, double atr) {
    double score = 0.4; // Base Score (40%)
    
    // 1. Trend Strength (Distance from Anchor): +15%
    if(MathAbs(fast - anchor) > atr * 1.5) score += 0.15;
    
    // 2. Momentum (Fast/Slow separation): +15%
    if(MathAbs(fast - slow) > atr * 0.3) score += 0.15;
    
    // 3. Confluence (HMA & ALMA Agreement): +15%
    // Assuming the calling logic verifies direction, here we reward clarity/smoothness
    score += 0.15; 
    
    // 4. Market Sentiment (Simulated Input from AI Agent Swarm): +15%
    // In production, this reads from 'sentiment_matrix.json' updated by the Python layer
    // Represents the collective sentiment of the swarm (e.g., "Aggressive Growth")
    double sentimentScore = 0.15; 
    score += sentimentScore;
    
    return MathMin(score, 1.0);
}

double GetDynamicLotSize(double slDistance, double confidence) {
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double riskAmount = equity * (BaseRiskPercent / 100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   
   if(slDistance == 0 || tickValue == 0 || tickSize == 0) return 0.01;
   
   double slPoints = slDistance / tickSize;
   double baseLot = riskAmount / (slPoints * tickValue);
   
   // Scale by confidence: Position size is directly proportional to confidence score.
   // Confidence 1.0 = Full Risk (BaseRiskPercent). Confidence 0.5 = Half Risk.
   double finalLot = baseLot * confidence;
   
   return MathMin(NormalizeDouble(finalLot, 2), MaxLotSize);
}

// --- ON TICK ---
void OnTick() {
   if(!IsNewCandle()) return;

   double fast[], slow[], anchor[], atr[], hma[], alma[];
   CopyBuffer(hFast, 0, 1, 2, fast);
   CopyBuffer(hSlow, 0, 1, 2, slow);
   CopyBuffer(hAnchor, 0, 1, 2, anchor);
   CopyBuffer(hATR, 0, 1, 1, atr);
   CopyBuffer(hHMA, 0, 1, 2, hma);
   CopyBuffer(hALMA, 0, 1, 2, alma);
   
   double close = iClose(_Symbol, PERIOD_H1, 1);
   double confidence = CalculateConfidence(fast[0], slow[0], anchor[0], hma[0], alma[0], atr[0]);
   
   // --- BUY LOGIC ---
   if(close > anchor[0] && fast[0] > anchor[0]) {
      if(fast[1] < slow[1] && fast[0] > slow[0]) {
          // Confirmation
          if(hma[0] > hma[1] && alma[0] > alma[1]) {
              double slDist = atr[0] * ATR_Multiplier;
              double sl = SymbolInfoDouble(_Symbol, SYMBOL_BID) - slDist;
              double tp = SymbolInfoDouble(_Symbol, SYMBOL_BID) + (slDist * 2.5);
              
              double lotSize = GetDynamicLotSize(slDist, confidence);
              trade.Buy(lotSize, _Symbol, SymbolInfoDouble(_Symbol, SYMBOL_ASK), sl, tp, "Hybrid Buy Conf=" + DoubleToString(confidence, 2));
          }
      }
   }

   // --- SELL LOGIC ---
   if(close < anchor[0] && fast[0] < anchor[0]) {
      if(fast[1] > slow[1] && fast[0] < slow[0]) {
          // Confirmation
          if(hma[0] < hma[1] && alma[0] < alma[1]) {
              double slDist = atr[0] * ATR_Multiplier;
              double sl = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + slDist;
              double tp = SymbolInfoDouble(_Symbol, SYMBOL_ASK) - (slDist * 2.5);
              
              double lotSize = GetDynamicLotSize(slDist, confidence);
              trade.Sell(lotSize, _Symbol, SymbolInfoDouble(_Symbol, SYMBOL_BID), sl, tp, "Hybrid Sell Conf=" + DoubleToString(confidence, 2));
          }
      }
   }
}`;

const XAUUSD_SWING_MQL5_CODE = `//+------------------------------------------------------------------+
//|                        XAUUSD_Swing_EMA_RSI.mq5                  |
//|                        Generated by VortigenOS                   |
//|                        Strategy: H1 Swing Trend Follow           |
//+------------------------------------------------------------------+
#property copyright "VortigenOS AI"
#property version   "1.0"
#property strict
#include <Trade\\Trade.mqh>

input int    EMA_Trend_Period = 50;   // Main Trend
input int    EMA_Swing_Period = 14;   // Swing Entry
input int    RSI_Period       = 14;   // Momentum
input int    StopLossPips     = 400;  // Fixed SL (points)
input double RewardRatio      = 2.0;  // TP = SL * Ratio
input double LotSize          = 0.01;

int hTrend, hSwing, hRSI;
CTrade trade;

int OnInit() {
   hTrend = iMA(_Symbol, PERIOD_H1, EMA_Trend_Period, 0, MODE_EMA, PRICE_CLOSE);
   hSwing = iMA(_Symbol, PERIOD_H1, EMA_Swing_Period, 0, MODE_EMA, PRICE_CLOSE);
   hRSI   = iRSI(_Symbol, PERIOD_H1, RSI_Period, PRICE_CLOSE);
   return(INIT_SUCCEEDED);
}

void OnTick() {
   double trend[], swing[], rsi[];
   double close1 = iClose(_Symbol, PERIOD_H1, 1);
   double open1  = iOpen(_Symbol, PERIOD_H1, 1);
   
   CopyBuffer(hTrend, 0, 1, 2, trend);
   CopyBuffer(hSwing, 0, 1, 2, swing);
   CopyBuffer(hRSI, 0, 1, 2, rsi);
   
   bool isBullishCandle = close1 > open1;
   bool isBearishCandle = close1 < open1;
   
   // BUY Logic
   // 1. Trend: Price > EMA50 & EMA14 > EMA50
   if(close1 > trend[0] && swing[0] > trend[0]) {
      // 2. Momentum: RSI > 50
      if(rsi[0] > 50) {
         // 3. Pullback & Entry: Close back above EMA14
         if(isBullishCandle && close1 > swing[0] && open1 < swing[0]) {
             trade.Buy(LotSize, _Symbol, 0, 
                 SymbolInfoDouble(_Symbol, SYMBOL_BID) - StopLossPips * _Point, 
                 SymbolInfoDouble(_Symbol, SYMBOL_BID) + (StopLossPips * RewardRatio * _Point), 
                 "Swing Buy");
         }
      }
   }

   // SELL Logic
   // 1. Trend: Price < EMA50 & EMA14 < EMA50
   if(close1 < trend[0] && swing[0] < trend[0]) {
      // 2. Momentum: RSI < 50
      if(rsi[0] < 50) {
         // 3. Pullback & Entry: Close back below EMA14
         if(isBearishCandle && close1 < swing[0] && open1 > swing[0]) {
             trade.Sell(LotSize, _Symbol, 0, 
                 SymbolInfoDouble(_Symbol, SYMBOL_ASK) + StopLossPips * _Point, 
                 SymbolInfoDouble(_Symbol, SYMBOL_ASK) - (StopLossPips * RewardRatio * _Point), 
                 "Swing Sell");
         }
      }
   }
}`;

const POLYMARKET_PY_CODE = `"""
🌙 Moon Dev's High-Performance Polymarket Agent
Architecture: AsyncIO + Token-Optimized Protocol + Modular Pipes
Optimization: Reduces AI Token Cost by ~60% vs JSON
"""

import asyncio
import aiohttp
import pandas as pd
import json
import os
import sys
import logging
from dataclasses import dataclass
from typing import List, Dict

# --- HIGH-PERFORMANCE CONFIGURATION ---
CONFIG = {
    "MIN_LIQUIDITY_USD": 5000,
    "SPREAD_THRESHOLD": 0.05,
    "BATCH_SIZE": 10,
    "CACHE_FILE": "data/polymarket/market_snapshot.parquet",
    "DECISION_FILE": "data/polymarket/decisions.json"
}

# Configure structured logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')

@dataclass
class Market:
    id: str
    question: str
    price: float
    volume: float
    spread: float

    def to_dense_token(self) -> str:
        """
        Optimization: Serialize to Pipe-Delimited String
        Saves ~40-60% tokens compared to JSON or verbose text.
        Format: ID|Q_TRUNC|P|V|S
        """
        q_trunc = self.question[:40].replace("|", "")
        return f"{self.id}|{q_trunc}|{self.price:.2f}|{self.volume:.0f}|{self.spread:.2f}"

class PolyAgentCore:
    def __init__(self):
        self.data_buffer = []

    async def stream_markets(self):
        """
        Async Websocket Consumer
        Connects to Gamma/Polymarket WS, filters noise, buffers high-value markets.
        """
        uri = "wss://ws-live-data.polymarket.com"
        logging.info(f"🚀 [STREAM] Connecting to {uri}...")
        
        # Simulated Async Loop for Mock
        while True:
            # In production: await ws.recv()
            # Here: Simulate receiving filtered, high-quality market data
            await asyncio.sleep(0.1) 
            # Logic: Buffer trades, dedup, and write to Parquet every N seconds
            pass

    async def ai_inference_engine(self):
        """
        Batch Inference Worker
        Reads snapshot -> Constructs Dense Prompts -> Queries Swarm -> Writes Decisions
        """
        logging.info("🧠 [INFER] Starting batch inference engine...")
        
        # Load Data Efficiently
        if not os.path.exists(CONFIG["CACHE_FILE"]):
            return

        df = pd.read_parquet(CONFIG["CACHE_FILE"])
        
        # 1. Pre-Filter (Zero Token Cost)
        # Don't waste AI tokens on low vol or high spread
        valid_markets = df[
            (df['volume'] > CONFIG["MIN_LIQUIDITY_USD"]) & 
            (df['spread'] < CONFIG["SPREAD_THRESHOLD"])
        ]

        # 2. Batch Processing
        batch = []
        for _, row in valid_markets.iterrows():
            batch.append(Market(
                id=row['market_id'], 
                question=row['question'], 
                price=row['price'], 
                volume=row['volume'],
                spread=row['spread']
            ))
            
            if len(batch) >= CONFIG["BATCH_SIZE"]:
                await self._process_batch(batch)
                batch = []

    async def _process_batch(self, markets: List[Market]):
        # 3. Dense Prompt Construction
        prompt_header = "ID|Q|P|V|S"
        prompt_body = "\\n".join([m.to_dense_token() for m in markets])
        full_prompt = (
            f"Analyze prediction markets.\\nFormat: ID|CONFIDENCE|DIRECTION|REASON_TOKEN\\n"
            f"{prompt_header}\\n{prompt_body}"
        )
        
        # 4. Cost-Efficient Query
        # logging.info(f"🌊 Sending {len(markets)} markets to Swarm ({len(full_prompt)} chars)")
        # response = await swarm.query(full_prompt)
        # self._save_decisions(response)
        pass

def main():
    """
    Modular Entry Point
    Allows running components independently for scaling.
    Usage: python polymarket_agent.py --mode [stream|infer|execute]
    """
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--mode', choices=['stream', 'infer', 'execute'], required=True)
    args = parser.parse_args()
    
    agent = PolyAgentCore()
    
    loop = asyncio.get_event_loop()
    if args.mode == 'stream':
        loop.run_until_complete(agent.stream_markets())
    elif args.mode == 'infer':
        loop.run_until_complete(agent.ai_inference_engine())

if __name__ == "__main__":
    main()
`;

export const STRATEGIES: Strategy[] = [
    { 
        name: 'Triangle Flag Breakout', 
        winRate: 0.538, 
        profitFactor: 1.35, 
        validation: 'EUR/USD 2003-2023', 
        edgeVsRandom: 2.12,
        parameters: { 'Pattern': 'Flag', 'Timeframe': 'M15', 'Breakout Vol': '>1.5x Avg' } 
    },
    { 
        name: 'RR=3 Short', 
        winRate: 0.612, 
        profitFactor: 1.82, 
        validation: 'STNE/EGAN Live 2025', 
        edgeVsRandom: 3.51,
        parameters: { 'Entry': 'VWAP Rejection', 'Stop': 'Session High', 'Target': '3R' }
    },
    { 
        name: 'Market Making', 
        winRate: 0.684, 
        profitFactor: 1.12, 
        validation: 'SPX Options', 
        edgeVsRandom: 4.25,
        parameters: { 'Spread': 'Dynamic', 'Inventory': 'Neutral', 'Latency': '<10ms' }
    },
    { 
        name: 'Gamma Scalping', 
        winRate: 0.721, 
        profitFactor: 1.45, 
        validation: 'Delta-neutral', 
        edgeVsRandom: 4.98,
        parameters: { 'Delta Limit': '200', 'Hedge Freq': 'Tick-based', 'Vega': 'Long' }
    },
    { 
        name: 'Order Flow Imbalance', 
        winRate: 0.557, 
        profitFactor: 1.28, 
        validation: 'Real-time', 
        edgeVsRandom: 2.78,
        parameters: { 'Imbalance %': '300%', 'Depth': 'L2', 'Lookback': '500ms' }
    },
    { 
        name: 'Macro Regime', 
        winRate: 0.643, 
        profitFactor: 1.19, 
        validation: 'SPX Daily', 
        edgeVsRandom: 3.05,
        parameters: { 'Factor': 'Real Yields', 'Correlation': '>0.8', 'Horizon': 'Weekly' }
    },
    { 
        name: 'Smart Money', 
        winRate: 0.589, 
        profitFactor: 1.31, 
        validation: 'ICT Concepts', 
        edgeVsRandom: 2.91,
        parameters: { 'Structure': 'Order Block', 'Session': 'Killzone', 'Fibs': '0.618' }
    },
    { 
        name: 'XAUUSD Hybrid EMA', 
        winRate: 0.715, 
        profitFactor: 2.45, 
        validation: 'XAUUSD Hybrid H1', 
        edgeVsRandom: 5.12,
        sourceCode: XAUUSD_MQL5_CODE,
        parameters: { 
            'Timeframe': 'H1', 
            'EMA Setup': '8/12/100',
            'Risk Model': 'Dynamic Confidence',
            'HMA Filter': 55,
            'ALMA Filter': 21,
            'Sentiment': 'AI Swarm Input',
            'Max Risk': '2.0%'
        }
    },
    {
        name: 'AI Agent Trading Bot',
        winRate: 0.65,
        profitFactor: 1.50,
        validation: 'Simulated Self-Play',
        edgeVsRandom: 1.2,
        parameters: { 
            'Autonomy': 'Level 4 (Autonomous)', 
            'Learning': 'Online RL', 
            'Goal': 'Alpha Generation',
            'Memory': 'Vector DB' 
        }
    },
    {
        name: 'XAUUSD Swing EMA-RSI',
        winRate: 0.675,
        profitFactor: 1.95,
        validation: 'XAUUSD H1 2024',
        edgeVsRandom: 3.85,
        sourceCode: XAUUSD_SWING_MQL5_CODE,
        parameters: {
            'Timeframe': 'H1',
            'EMA Trend': 50,
            'EMA Swing': 14,
            'RSI': 14,
            'Risk': '400 pips Fixed'
        }
    },
    {
        name: 'Polymarket Prediction Agent',
        winRate: 0.72,
        profitFactor: 2.10,
        validation: 'Live Consensus 2025',
        edgeVsRandom: 4.50,
        sourceCode: POLYMARKET_PY_CODE,
        parameters: {
            'Mode': 'Swarm Consensus',
            'Min Trade': '$500',
            'Ignore Threshold': '0.02',
            'AI Provider': 'xAI/Grok',
            'Lookback': '24h'
        }
    }
];

const COLLECTIVE_STATE: CollectiveState = {
    sentiment: 'Calculated Risk',
    lastMeetingSummary: 'Consensus reached to increase exposure to volatility-based strategies (Gamma Scalping) while moderately reducing macro-regime allocation due to shifting VIX term structure.',
    operationalFocus: 'Capitalize on short-term vol spikes in equity indices via causal arbitrage models.',
    activeTaskForces: [
        { name: 'Task Force Alpha', objective: 'Cross-asset volatility arbitrage.', members: ['GS_1', 'GS_3', 'OFI_2'] },
        { name: 'Task Force Gamma', objective: 'High-frequency order flow analysis in crypto futures.', members: ['SMC_4', 'SMC_5', 'OFI_6'] }
    ]
};

const agentTypeMap: Record<StrategyType, AgentType> = {
    'Triangle Flag Breakout': 'Bot',
    'RR=3 Short': 'Bot',
    'Market Making': 'Bot',
    'Order Flow Imbalance': 'Bot',
    'Gamma Scalping': 'Agent',
    'Macro Regime': 'Agent',
    'Smart Money': 'Agent',
    'XAUUSD Hybrid EMA': 'Bot',
    'AI Agent Trading Bot': 'Bot',
    'XAUUSD Swing EMA-RSI': 'Bot',
    'Polymarket Prediction Agent': 'Agent',
};

const generateAgents = (): Agent[] => {
    const agents: Agent[] = [];
    const strategyMap: { [key in StrategyType]: { count: number, symbols: string[] } } = {
        'Triangle Flag Breakout': { count: 8, symbols: ['EUR/USD', 'GBP/USD', 'SPY'] },
        'RR=3 Short': { count: 8, symbols: ['QQQ', 'TSLA', 'NVDA'] },
        'Market Making': { count: 6, symbols: ['SPXW', 'NDX'] },
        'Gamma Scalping': { count: 5, symbols: ['SPY', 'VIX'] },
        'Order Flow Imbalance': { count: 7, symbols: ['ES=F', 'NQ=F'] },
        'Macro Regime': { count: 4, symbols: ['^VIX', 'GLD', 'TLT'] },
        'Smart Money': { count: 6, symbols: ['BTC-USD', 'ETH-USD'] },
        'XAUUSD Hybrid EMA': { count: 5, symbols: ['XAUUSD'] },
        'AI Agent Trading Bot': { count: 5, symbols: ['BTC-USD', 'ETH-USD', 'SOL-USD'] },
        'XAUUSD Swing EMA-RSI': { count: 5, symbols: ['XAUUSD'] },
        'Polymarket Prediction Agent': { count: 5, symbols: ['Poly/Trump', 'Poly/FedRates', 'Poly/Bitcoin'] },
    };

    STRATEGIES.forEach(strategy => {
        const config = strategyMap[strategy.name];
        for (let i = 0; i < config.count; i++) {
            const id = `${strategy.name.split(' ').map(s => s[0]).join('')}_${i + 1}`;
            const status_rand = Math.random();
            let collaboration: string | undefined = undefined;
            COLLECTIVE_STATE.activeTaskForces.forEach(tf => {
                if (tf.members.includes(id)) {
                    collaboration = tf.name;
                }
            });
            
            // Assign lightweight tools based on strategy
            let tools: string[] = [];
            if (strategy.name === 'XAUUSD Hybrid EMA') {
                tools = ['hybrid_ema.py', 'volatility_guard.js', 'trend_scanner.sh', 'executor_mt5.py', 'hybrid_ema_system.mq5'];
            } else if (strategy.name === 'Triangle Flag Breakout') {
                 tools = ['pattern_recognition.cpp', 'market_depth.sh'];
            } else if (strategy.name === 'AI Agent Trading Bot') {
                 tools = ['autonomous_core.py', 'goal_seeker.js', 'memory_db.json'];
            } else if (strategy.name === 'XAUUSD Swing EMA-RSI') {
                 tools = ['swing_scanner.py', 'rsi_calc.js', 'xau_swing_ea.mq5'];
            } else if (strategy.name === 'Polymarket Prediction Agent') {
                 tools = ['polymarket_agent.py', 'consensus_engine.py', 'swarm_config.json'];
            } else {
                 tools = ['scraper_generic.js', 'sentiment_analyzer.py', 'execution_guard.sh'];
            }

            agents.push({
                id,
                type: agentTypeMap[strategy.name],
                strategy: strategy.name,
                status: status_rand < 0.8 ? 'active' : (status_rand < 0.9 ? 'monitoring' : (status_rand < 0.95 ? 'inactive' : 'error')),
                symbols: config.symbols,
                pnl: (Math.random() - 0.45) * 5000,
                trades: Math.floor(Math.random() * 20) + 5,
                collaboration,
                genomeVersion: `v1.${Math.floor(Math.random() * 5)}.${Math.floor(Math.random() * 10)}`,
                fitnessScore: 0.95 + (Math.random() * 0.1),
                genes: {
                    risk_tolerance: Math.random() * 0.5 + 0.5, // 0.5 - 1.0
                    adaptation_speed: Math.random() * 0.5 + 0.5, // 0.5 - 1.0
                    data_source_preference: Math.random() // 0.0 - 1.0
                },
                tools: tools
            });
        }
    });
    return agents.slice(0, 65); // Increased limit to accommodate new agents
};

const generatePnlHistory = (initialPnl: number): { time: string; pnl: number }[] => {
    const data = [];
    let currentPnl = initialPnl;
    const now = new Date();
    for (let i = 180; i >= 0; i--) {
        const time = new Date(now.getTime() - i * 60000);
        currentPnl += (Math.random() - 0.5) * 2000;
        data.push({
            time: time.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false }),
            pnl: Math.round(currentPnl)
        });
    }
    return data;
};

const LOG_MESSAGES: { level: LogLevel; message: string; agent?: boolean }[] = [
    { level: 'INFO', message: 'Executing trade on {symbol}. Size: {size} units.', agent: true },
    { level: 'INFO', message: 'Monitoring price action near key level for {strategy} setup.', agent: true },
    { level: 'WARN', message: 'Slippage detected on order execution for agent {agentId}.', agent: true },
    { level: 'CRITICAL', message: 'Risk parameter breached for agent {agentId}. Reducing exposure.', agent: true },
];

export const generateLogEntry = (agents: Agent[]): AuditLog => {
    const template = LOG_MESSAGES[Math.floor(Math.random() * LOG_MESSAGES.length)];
    const randomAgent = agents[Math.floor(Math.random() * agents.length)];
    
    let message = template.message;
    if (template.agent) {
        message = message.replace('{agentId}', randomAgent.id)
                         .replace('{symbol}', randomAgent.symbols[0])
                         .replace('{size}', (Math.random() * 100).toFixed(2))
                         .replace('{strategy}', randomAgent.strategy);
    }

    return {
        id: new Date().toISOString() + Math.random(),
        timestamp: new Date().toISOString(),
        level: template.level,
        message: message,
        agentId: template.agent ? randomAgent.id : undefined
    };
};

const generateInitialAuditLogs = (agents: Agent[], count: number): AuditLog[] => {
    return Array.from({ length: count }, () => generateLogEntry(agents));
};

const generateEvolutionHistory = (): EvolutionHistoryPoint[] => {
    const history: EvolutionHistoryPoint[] = [];
    let currentFitness = 1.05;
    const now = Date.now();
    for (let i = 60; i >= 0; i--) {
        history.push({
            timestamp: now - i * 60000 * 5, // 5 minutes per point
            fitness: currentFitness
        });
        currentFitness += (Math.random() - 0.4) * 0.01;
    }
    return history;
};

const generateDataSources = (): DataSource[] => {
    return [
        { id: 'DS_001', type: 'API', sourceName: 'Quandl Real-Time Futures', status: 'Active', integrityScore: 0.98, lastUpdated: new Date(Date.now() - 1000 * 60 * 5).toISOString() },
        { id: 'DS_002', type: 'Satellite Imagery', sourceName: 'Star-Omega-7 Crude Oil Storage', status: 'Evaluating', integrityScore: 0.85, lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
        { id: 'DS_003', type: 'Decentralized Oracle', sourceName: 'Chainlink VIX Feed', status: 'Active', integrityScore: 0.99, lastUpdated: new Date(Date.now() - 1000 * 60 * 2).toISOString() },
        { id: 'DS_004', type: 'Knowledge Graph', sourceName: 'Project Unum Geopolitical Events', status: 'Integrating', integrityScore: 0.92, lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
        { id: 'DS_005', type: 'API', sourceName: 'Novel Sentiment API (Social-Pulse)', status: 'Rejected', integrityScore: 0.45, lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString() },
        { id: 'DS_006', type: 'Quantum Entropy', sourceName: 'ANU Quantum Random Numbers Server', status: 'Active', integrityScore: 1.00, lastUpdated: new Date(Date.now() - 1000 * 60 * 1).toISOString() },
        { id: 'DS_007', type: 'API', sourceName: 'Dark Pool Volume Feed', status: 'Discovered', integrityScore: 0.77, lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString() },
    ];
};

const generateInitialConsensusSignals = (agents: Agent[]): ConsensusSignal[] => {
    const resolvedSignal1: ConsensusSignal = {
        id: `CS-${Date.now() - 60000}`,
        proposingAgentId: 'SMC_2',
        symbol: 'BTC-USD',
        side: 'Buy',
        strategy: 'Smart Money',
        status: 'approved',
        eligibleVoters: agents.filter(a => a.strategy === 'Smart Money').map(a => a.id),
        votes: [
            { agentId: 'SMC_1', decision: 'yes' },
            { agentId: 'SMC_3', decision: 'yes' },
            { agentId: 'SMC_4', decision: 'no' },
            { agentId: 'SMC_5', decision: 'yes' },
            { agentId: 'SMC_6', decision: 'yes' },
        ],
        timestamp: new Date(Date.now() - 120000).toISOString(),
        resolvedTimestamp: new Date(Date.now() - 60000).toISOString(),
    };
     const resolvedSignal2: ConsensusSignal = {
        id: `CS-${Date.now() - 180000}`,
        proposingAgentId: 'TFB_5',
        symbol: 'SPY',
        side: 'Sell',
        strategy: 'Triangle Flag Breakout',
        status: 'rejected',
        eligibleVoters: agents.filter(a => a.strategy === 'Triangle Flag Breakout').map(a => a.id),
        votes: [
            { agentId: 'TFB_1', decision: 'no' },
            { agentId: 'TFB_2', decision: 'no' },
            { agentId: 'TFB_3', decision: 'yes' },
            { agentId: 'TFB_4', decision: 'no' },
            { agentId: 'TFB_6', decision: 'no' },
            { agentId: 'TFB_7', decision: 'abstain' },
            { agentId: 'TFB_8', decision: 'no' },
        ],
        timestamp: new Date(Date.now() - 240000).toISOString(),
        resolvedTimestamp: new Date(Date.now() - 180000).toISOString(),
    };
    return [resolvedSignal1, resolvedSignal2];
};

const AI_BOARD_STATE: AIBoardState = {
    status: 'Nominal',
    costProjection: 85, // Monthly cost
    members: [
        { id: 'BOD_1', modelName: 'DeepSeek-V2', role: 'Chief Strategist', status: 'Online' },
        { id: 'BOD_2', modelName: 'Qwen-Max', role: 'Chief Economist', status: 'Online' },
        { id: 'BOD_3', modelName: 'GPT-4o', role: 'Compliance Officer', status: 'Online' },
        { id: 'BOD_4', modelName: 'Grok-2', role: 'Risk Arbiter', status: 'Recalibrating' },
    ],
    directives: [
        { id: `DIR-${Date.now() - 120000}`, timestamp: new Date(Date.now() - 120000).toISOString(), sourceModel: 'DeepSeek-V2', directive: 'Increase agent autonomy in high-frequency regimes with elevated fitness scores.'},
        { id: `DIR-${Date.now() - 600000}`, timestamp: new Date(Date.now() - 600000).toISOString(), sourceModel: 'Qwen-Max', directive: 'Re-evaluate macro correlations in response to shifting central bank forward guidance.'},
    ],
};

const QUANTUM_ADDONS: QuantumAddon[] = [
    { name: 'eDNA', code: 'addons/eDNA/', description: 'Self-modifying agent genome', status: 'ACTIVE' },
    { name: 'ZKMP', code: 'addons/ZKMP/', description: 'Zero-knowledge market proofs', status: 'ACTIVE' },
    { name: 'TAU', code: 'addons/TAU/', description: 'Temporal arbitrage prediction', status: 'ACTIVE' },
    { name: 'GET', code: 'addons/GET/', description: 'Global economic twin', status: 'ACTIVE' },
    { name: 'AEG', code: 'addons/AEG/', description: 'Axiomatic ethics governor', status: 'ACTIVE' },
    { name: 'MCGC', code: 'addons/MCGC/', description: 'Code self-modification', status: 'DEV' },
    { name: 'SNRF', code: 'addons/SNRF/', description: 'Synthetic narrative forge', status: 'DEV' },
    { name: 'QEC', code: 'addons/QEC/', description: 'Quantum entanglement channel', status: 'FUTURE' },
    { name: 'EOF', code: 'addons/EOF/', description: 'Emergent objective function', status: 'FUTURE' },
    { name: 'Manifold', code: 'addons/Manifold/', description: 'Market geometry engine', status: 'FUTURE' },
];

const MODEL_ROUTES: ModelRoute[] = [
    {
        taskType: 'TRADE_ADVICE',
        primaryModel: 'DeepSeek-V2',
        description: 'High-level strategic decisions on trade entry, exit, and sizing.'
    },
    {
        taskType: 'EXECUTION_ADVICE',
        primaryModel: 'DeepSeek-V2',
        description: 'Optimal execution logic, minimizing slippage and market impact.'
    },
    {
        taskType: 'REASONING',
        primaryModel: 'DeepSeek-V2',
        fallbackModel: 'GPT-4o',
        description: 'Complex problem-solving, causal inference, and logical deduction.'
    },
    {
        taskType: 'LONG_CONTEXT',
        primaryModel: 'Qwen-Max',
        fallbackModel: 'GPT-4o',
        description: 'Analysis of extensive logs, research papers, and market history.'
    },
    {
        taskType: 'SAFETY',
        primaryModel: 'GPT-4o',
        fallbackModel: 'DeepSeek-V2',
        description: 'Compliance checks, ethical governance, and risk override validation.'
    },
];

const generatePredictions = (): Prediction[] => {
    const symbols = ['BTC-USD', 'SPY', 'NVDA', 'EUR/USD', 'TSLA', 'GLD', 'XAUUSD'];
    const horizons: Array<'1d' | '7d' | '30d'> = ['1d', '7d', '30d'];
    const r_tokens_pool = ["trend_down", "liquidity_thin", "entry_unconfirmed", "volume_spike", "macro_catalyst", "positive_sentiment", "insider_activity", "ema_cross"];
    const predictions: Prediction[] = [];

    symbols.forEach(symbol => {
        horizons.forEach(horizon => {
            const id = `${symbol}-${horizon}-${Date.now()}`;
            const predictedReturn = (Math.random() - 0.48) * 0.1;
            const uncertainty = Math.random() * 0.05;
            const confidence = Math.max(0.4, 1 - (uncertainty / (Math.abs(predictedReturn) + 1e-9)));
            const probabilityPositive = predictedReturn > 0 ? Math.min(0.95, confidence + 0.1) : Math.max(0.05, 1 - (confidence + 0.1));
            
            const daysMap = {"1d":1, "7d":7, "30d":30};
            const normalizedReturn = predictedReturn / daysMap[horizon];
            const edgeScore = normalizedReturn * probabilityPositive * confidence;

            const passesFilters = probabilityPositive > 0.7 && confidence > 0.6;
            
            let decision: 'Buy' | 'Sell' | 'Hold' = 'Hold';
            if (passesFilters) {
                if (predictedReturn > 0) decision = 'Buy';
                else decision = 'Sell';
            }

            predictions.push({
                id,
                symbol,
                horizon,
                predictedReturn,
                uncertainty,
                confidence,
                probabilityPositive,
                decision,
                reasoning: `Based on multi-factor analysis, the model predicts a ${predictedReturn > 0 ? 'positive' : 'negative'} drift over the ${horizon} horizon, driven by key reasoning tokens.`,
                risks: ["Market volatility", "Geopolitical events"],
                r_tokens: r_tokens_pool.sort(() => 0.5 - Math.random()).slice(0, 3),
                edgeScore,
                passesFilters,
            });
        });
    });

    return predictions.sort((a,b) => b.edgeScore - a.edgeScore);
};

const AGENTS = generateAgents();
const TOTAL_PNL = AGENTS.reduce((sum, agent) => sum + agent.pnl, 0);
const EVOLUTION_HISTORY = generateEvolutionHistory();

export const MOCK_SYSTEM_STATE: SystemState = {
    agents: AGENTS,
    strategies: STRATEGIES,
    pnl: TOTAL_PNL,
    drawdown: 0.084,
    pnlHistory: generatePnlHistory(TOTAL_PNL - 30000),
    circuitBreaker: {
        dailyLoss: 0.021,
        dailyLossLimit: 0.05,
        maxDrawdown: 0.084,
        maxDrawdownLimit: 0.15,
        status: 'SAFE'
    },
    collectiveState: COLLECTIVE_STATE,
    auditLogs: generateInitialAuditLogs(AGENTS, 50),
    evolutionaryState: {
        currentFitness: EVOLUTION_HISTORY[EVOLUTION_HISTORY.length - 1].fitness,
        mutations: 137,
        history: EVOLUTION_HISTORY,
        lastMutation: null,
    },
    consensusSignals: generateInitialConsensusSignals(AGENTS),
    dataSources: generateDataSources(),
    aiBoardState: AI_BOARD_STATE,
    quantumAddons: QUANTUM_ADDONS,
    modelRoutes: MODEL_ROUTES,
    predictions: generatePredictions(),
    boardEvents: [],
};

export const triggerEvolutionEvent = (prevState: SystemState): SystemState => {
    // Performance Optimization: Avoid full array copy if only one agent changes.
    const agents = [...prevState.agents]; 
    
    // 1. Selection: Find a low-performing agent (Reference kept, index needed)
    let targetAgent = agents[0];
    let targetIndex = 0;
    
    for (let i = 1; i < agents.length; i++) {
        if (agents[i].fitnessScore < targetAgent.fitnessScore) {
            targetAgent = agents[i];
            targetIndex = i;
        }
    }

    // Clone only the target agent to mutate
    const mutatedAgent = { ...targetAgent, genes: { ...targetAgent.genes } };

    // 2. Mutation: Pick a gene and mutate it
    const genes: (keyof Agent['genes'])[] = ['risk_tolerance', 'adaptation_speed', 'data_source_preference'];
    const geneToMutate = genes[Math.floor(Math.random() * genes.length)];
    
    const oldValue = mutatedAgent.genes[geneToMutate];
    const newValue = Math.max(0.1, Math.min(1.0, oldValue + (Math.random() - 0.5) * 0.2)); // Mutate by up to +/- 0.1
    mutatedAgent.genes[geneToMutate] = newValue;
    
    // 3. Evaluation: Update genome and fitness
    const oldVersionParts = mutatedAgent.genomeVersion.split('.').map(Number);
    mutatedAgent.genomeVersion = `v${oldVersionParts[0]}.${oldVersionParts[1] + 1}.${Math.floor(Math.random()*10)}`;
    const oldFitness = mutatedAgent.fitnessScore;
    mutatedAgent.fitnessScore *= (1 + (Math.random() * 0.05)); // Increase fitness by up to 5%

    // Replace in array
    agents[targetIndex] = mutatedAgent;

    // 4. Logging: Create a detailed audit log
    const reason = oldFitness < 0.9 ? 'performance decay' : 'environmental drift';
    const evolutionLog: AuditLog = {
        id: new Date().toISOString() + Math.random(),
        timestamp: new Date().toISOString(),
        level: 'EVOLUTION',
        agentId: mutatedAgent.id,
        message: `Genome mutated due to ${reason}. Gene '${geneToMutate}' changed from ${oldValue.toFixed(2)} to ${newValue.toFixed(2)}. Fitness increased to ${mutatedAgent.fitnessScore.toFixed(4)}.`
    };
    
    // 5. Update State
    const newFitness = agents.reduce((acc, agent) => acc + agent.fitnessScore, 0) / agents.length;
    const newHistory = [...prevState.evolutionaryState.history.slice(1), { timestamp: Date.now(), fitness: newFitness }];

    return {
        ...prevState,
        agents: agents, // New array, but mostly same object references.
        auditLogs: [evolutionLog, ...prevState.auditLogs].slice(0, 100),
        evolutionaryState: {
            currentFitness: newFitness,
            mutations: prevState.evolutionaryState.mutations + 1,
            history: newHistory,
            lastMutation: {
                agentId: mutatedAgent.id,
                gene: geneToMutate,
                oldValue,
                newValue,
                reason,
            }
        }
    };
};

export const processConsensusEvents = (prevState: SystemState): SystemState => {
    const newState = { 
        ...prevState, 
        consensusSignals: [...prevState.consensusSignals.map(s => ({...s, votes: [...s.votes]}))],
        auditLogs: [...prevState.auditLogs],
    };

    // 1. Chance to create a new signal if there are no pending ones
    const hasPendingSignals = newState.consensusSignals.some(s => s.status === 'pending');
    if (!hasPendingSignals && Math.random() < 0.2) { // 20% chance every cycle to create a new one
        const proposingAgent = newState.agents[Math.floor(Math.random() * newState.agents.length)];
        const eligibleVoters = newState.agents
            .filter(a => a.strategy === proposingAgent.strategy && a.id !== proposingAgent.id)
            .map(a => a.id);
        
        if (eligibleVoters.length > 2) {
            const newSignal: ConsensusSignal = {
                id: `CS-${Date.now()}`,
                proposingAgentId: proposingAgent.id,
                symbol: proposingAgent.symbols[Math.floor(Math.random() * proposingAgent.symbols.length)],
                side: Math.random() > 0.5 ? 'Buy' : 'Sell',
                strategy: proposingAgent.strategy,
                status: 'pending',
                votes: [],
                eligibleVoters,
                timestamp: new Date().toISOString(),
            };
            newState.consensusSignals.unshift(newSignal);

            const newLog: AuditLog = {
                id: `log-${Date.now()}`,
                timestamp: new Date().toISOString(),
                level: 'CONSENSUS',
                message: `New trade signal proposed by ${newSignal.proposingAgentId} for ${newSignal.side} ${newSignal.symbol}. Awaiting consensus from ${newSignal.eligibleVoters.length} agents.`
            };
            newState.auditLogs.unshift(newLog);
        }
    }

    // 2. Process votes for pending signals
    const pendingSignal = newState.consensusSignals.find(s => s.status === 'pending');
    if (pendingSignal) {
        // Find an agent who hasn't voted yet
        const voterId = pendingSignal.eligibleVoters.find(vId => !pendingSignal.votes.some(vote => vote.agentId === vId));

        if (voterId) {
            // Simulate a vote
            const rand = Math.random();
            const decision: VoteDecision = rand < 0.65 ? 'yes' : (rand < 0.9 ? 'no' : 'abstain');
            pendingSignal.votes.push({ agentId: voterId, decision });

            // 3. Check for resolution
            const yesVotes = pendingSignal.votes.filter(v => v.decision === 'yes').length;
            const noVotes = pendingSignal.votes.filter(v => v.decision === 'no').length;
            const totalVotes = pendingSignal.votes.length;
            const majorityThreshold = Math.ceil(pendingSignal.eligibleVoters.length / 2);

            let resolved = false;
            let newLog: AuditLog | null = null;

            // Resolve if one side gets a majority of ALL eligible voters
            if (yesVotes >= majorityThreshold) {
                pendingSignal.status = 'approved';
                resolved = true;
            } else if (noVotes >= majorityThreshold) {
                pendingSignal.status = 'rejected';
                resolved = true;
            } 
            // Or if all have voted
            else if (totalVotes === pendingSignal.eligibleVoters.length) {
                pendingSignal.status = yesVotes > noVotes ? 'approved' : 'rejected';
                resolved = true;
            }

            if (resolved) {
                pendingSignal.resolvedTimestamp = new Date().toISOString();
                newLog = {
                    id: `log-${Date.now()}`,
                    timestamp: new Date().toISOString(),
                    level: 'CONSENSUS',
                    message: `Consensus Reached for ${pendingSignal.side} ${pendingSignal.symbol}: ${pendingSignal.status.toUpperCase()} (${yesVotes} Yes / ${noVotes} No).`
                };
                newState.auditLogs.unshift(newLog);
            }
        }
    }

    // Cap consensus signals history
    newState.consensusSignals = newState.consensusSignals.slice(0, 20);

    return newState;
};

export const processAIBoardEvents = (prevState: SystemState): SystemState => {
    const newState = { 
        ...prevState, 
        aiBoardState: {
            ...prevState.aiBoardState,
            members: [...prevState.aiBoardState.members.map(m => ({...m}))],
            directives: [...prevState.aiBoardState.directives],
        },
        auditLogs: [...prevState.auditLogs],
    };

    // Chance for a member to change status
    if (Math.random() < 0.1) {
        const member = newState.aiBoardState.members.find(m => m.status === 'Recalibrating');
        if (member) {
            member.status = 'Online';
        } else {
            const onlineMember = newState.aiBoardState.members.find(m => m.status === 'Online');
            if (onlineMember) onlineMember.status = 'Recalibrating';
        }
    }
    
    // Chance for a new directive
    if (Math.random() < 0.15) {
        const onlineMembers = newState.aiBoardState.members.filter(m => m.status === 'Online');
        if (onlineMembers.length > 0) {
            const author = onlineMembers[Math.floor(Math.random() * onlineMembers.length)];
            const directives = [
                'Authorize Task Force Omega to explore quantum entanglement channels for data integrity verification.',
                'Mandate a system-wide recalibration of risk models based on emergent geopolitical narratives.',
                'Shift collective sentiment towards Defensive posture pending resolution of liquidity squeeze scenario.',
                'Prioritize evolution of agents demonstrating high fitness in volatile, low-liquidity environments.',
            ];
            const newDirective: AIBoardDirective = {
                id: `DIR-${Date.now()}`,
                timestamp: new Date().toISOString(),
                sourceModel: author.modelName,
                directive: directives[Math.floor(Math.random() * directives.length)],
            };
            newState.aiBoardState.directives.unshift(newDirective);
            newState.aiBoardState.directives = newState.aiBoardState.directives.slice(0, 10);

            const newLog: AuditLog = {
                 id: `log-${Date.now()}`,
                timestamp: new Date().toISOString(),
                level: 'BOARD',
                message: `New Board Directive from ${author.modelName}: "${newDirective.directive}"`
            };
             newState.auditLogs.unshift(newLog);
        }
    }

    return newState;
};

export const processBoardroomEvents = (prevState: SystemState): SystemState => {
    const newState = { ...prevState, boardEvents: [...prevState.boardEvents] };

    const r_tokens_pool = ["trend_down", "liquidity_thin", "entry_unconfirmed", "volume_spike", "macro_catalyst", "positive_sentiment", "insider_activity", "risk_aversion_high"];

    const generateVote = (modelName: AIBoardModel): ModelVote => {
        const confidence = Math.random() * 0.3 + 0.65; // 0.65 - 0.95
        const decision: 'approve' | 'reject' | 'hold' = Math.random() > 0.3 ? 'approve' : (Math.random() > 0.5 ? 'reject' : 'hold');
        return {
            modelName,
            decision,
            confidence,
            reasoning: `Analysis based on ${modelName}'s core competency. Confidence at ${(confidence * 100).toFixed(1)}%.`,
            r_tokens: r_tokens_pool.sort(() => 0.5 - Math.random()).slice(0, 2),
            risks: Math.random() > 0.7 ? ["elevated_volatility"] : [],
        };
    };

    const deepseekVote = generateVote('DeepSeek-V2');
    const qwenVote = generateVote('Qwen-Max');
    const gptVote = generateVote('GPT-4o');
    gptVote.decision = Math.random() > 0.1 ? 'approve' : 'reject'; // GPT is mostly a safety check

    const votes = [deepseekVote, qwenVote, gptVote];
    let finalDecision: ModelVote;
    let conflictDetected = false;

    // Consensus logic
    if (gptVote.decision === 'reject') {
        finalDecision = { ...gptVote, reasoning: `Compliance override: ${gptVote.reasoning}`};
    } else {
        const approveVotes = votes.filter(v => v.decision === 'approve').length;
        if (approveVotes >= 2) {
            finalDecision = deepseekVote.confidence > qwenVote.confidence ? deepseekVote : qwenVote;
            finalDecision.decision = 'approve';
        } else {
            finalDecision = deepseekVote.confidence > qwenVote.confidence ? deepseekVote : qwenVote;
            finalDecision.decision = 'hold';
        }
    }
    
    if (deepseekVote.decision !== qwenVote.decision) {
        conflictDetected = true;
    }

    const consensusScore = votes.reduce((acc, v) => acc + v.confidence, 0) / votes.length;
    
    const newEvent: BoardEvent = {
        id: `BE-${Date.now()}`,
        timestamp: new Date().toISOString(),
        agentRequest: {
            agentId: prevState.agents[Math.floor(Math.random() * prevState.agents.length)].id,
            task: `Evaluate trade signal on ${prevState.agents[0].symbols[0]}`
        },
        votes,
        finalDecision,
        consensusScore,
        conflictDetected
    };

    newState.boardEvents.unshift(newEvent);
    newState.boardEvents = newState.boardEvents.slice(0, 20);

    return newState;
};
