import React from 'react';
import { Activity as ActivityIcon, Download, Clock } from 'lucide-react';
import { useAppContext } from '../../context/AppContext';
import { Activity as ActivityType } from '../../types';

const Activity: React.FC = () => {
    const { state } = useAppContext();
    const { activities } = state;

    const getActivityColor = (type: string) => {
        const colors: Record<ActivityType['type'], string> = {
            'EXECUTION': 'border-cyan-500 text-cyan-400',
            'DECISION': 'border-purple-500 text-purple-400',
            'ALERT': 'border-yellow-500 text-yellow-400',
            'SYSTEM': 'border-slate-600 text-slate-400',
            'ERROR': 'border-red-500 text-red-400'
        };
        return colors[type as ActivityType['type']] || 'border-slate-700 text-slate-300';
    };

    const downloadCSV = () => {
        const headers = "id,timestamp,type,agent,message,temporalAlpha\n";
        const csvContent = activities.map(a => 
            `${a.id},"${a.timestamp}","${a.type}","${a.agent}","${a.message.replace(/"/g, '""')}",${a.temporalAlpha || ''}`
        ).join("\n");

        const blob = new Blob([headers + csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement("a");
        if (link.download !== undefined) {
            const url = URL.createObjectURL(blob);
            link.setAttribute("href", url);
            link.setAttribute("download", `vortigen_activity_log_${new Date().toISOString()}.csv`);
            link.style.visibility = 'hidden';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    };


    return (
        <div>
            <div className="flex justify-between items-center mb-6">
                <h2 className="text-3xl font-bold flex items-center gap-3"><ActivityIcon size={28} className="text-cyan-400"/> Live Activity Feed</h2>
                <button
                    onClick={downloadCSV}
                    className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-sm font-semibold"
                >
                    <Download size={16} />
                    Download as CSV
                </button>
            </div>
            <div className="space-y-3">
                {activities.map(activity => (
                    <div key={activity.id} className={`bg-slate-900 rounded-lg border-l-4 ${getActivityColor(activity.type)} p-4`}>
                        <div className="flex justify-between">
                            <div>
                                <div className="font-bold uppercase text-sm">{activity.type}</div>
                                <p className="text-slate-300 text-sm mt-1">{activity.message}</p>
                                <div className="flex items-center gap-4">
                                    <p className="text-xs text-slate-500 mt-1">Source: {activity.agent} • {new Date(activity.timestamp).toLocaleTimeString()}</p>
                                    {activity.temporalAlpha && (
                                        <div className="flex items-center gap-1 text-xs text-purple-400 font-semibold" title="Profit generated by the Temporal Arbitrage Unit by acting on micro-future predictions.">
                                            <Clock size={12} />
                                            <span>Temporal Alpha: +${activity.temporalAlpha.toFixed(2)}</span>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Activity;