
import React from 'react';
import { Users, Loader2, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';
import { useAppContext } from '../../context/AppContext';
import DashboardCard from '../DashboardCard';
import { ForumDebate, BoardAdvice, BoardConsultation, UnifiedSchemaV2 } from '../../types';
import StructuredAdviceCard from '../StructuredAdviceCard';

const BoardMemberCard: React.FC<{ model: string, specialty: string, status: 'online' | 'degraded' }> = ({ model, specialty, status }) => {
    const isOnline = status === 'online';
    return (
        <div className="bg-slate-900 rounded-lg p-4 border border-slate-800">
            <div className="flex justify-between items-start">
                <div>
                    <h3 className="font-bold text-lg">{model}</h3>
                    <p className="text-sm text-slate-400">{specialty}</p>
                </div>
                <div className={`flex items-center gap-1.5 text-xs font-semibold px-2 py-1 rounded-full ${isOnline ? 'bg-green-500/20 text-green-300' : 'bg-yellow-500/20 text-yellow-300'}`}>
                    <div className={`w-2 h-2 rounded-full ${isOnline ? 'bg-green-400' : 'bg-yellow-400'}`}></div>
                    {status}
                </div>
            </div>
        </div>
    );
};

const DecisionLog: React.FC<{ debate: ForumDebate }> = ({ debate }) => {
    if (!debate.finalBoardDecision) return null;

    const finalDecision = debate.finalBoardDecision.decision;
    const finalDecisionColor = ['reject', 'HALT'].includes(finalDecision) ? 'text-red-400' : 'text-green-400';

    return (
        <div className="bg-slate-800/50 p-4 rounded-lg">
            <div className="flex justify-between items-center mb-3">
                <div>
                    <p className="text-sm font-semibold">{debate.topic}</p>
                    <p className="text-xs text-slate-500">{new Date(debate.id).toLocaleString()}</p>
                </div>
                <div className={`text-lg font-bold ${finalDecisionColor} capitalize`}>{finalDecision}</div>
            </div>
            <StructuredAdviceCard advice={debate.finalBoardDecision} isMinimized />
        </div>
    );
};

const ManualConsultationCard: React.FC<{ consultation: BoardConsultation }> = ({ consultation }) => {
    return (
        <div className="bg-slate-800/50 p-4 rounded-lg">
            <div className="flex justify-between items-start mb-3">
                <div>
                    <p className="text-xs text-slate-400">
                        <span className="font-bold">{consultation.agentName}</span> requested <span className="font-bold">{consultation.taskType.replace('_', ' ')}</span>
                    </p>
                    <p className="text-sm font-semibold italic text-slate-300">"{consultation.request}"</p>
                    <p className="text-xs text-slate-500 mt-1">{new Date(consultation.timestamp).toLocaleString()}</p>
                </div>
                {consultation.status === 'pending' ? (
                     <span className="flex items-center gap-1.5 text-xs font-semibold px-2 py-1 rounded-full bg-yellow-500/20 text-yellow-300">
                        <Loader2 size={12} className="animate-spin" /> Pending...
                    </span>
                ) : (
                    <span className="flex items-center gap-1.5 text-xs font-semibold px-2 py-1 rounded-full bg-green-500/20 text-green-300">
                        <CheckCircle size={12} /> Complete
                    </span>
                )}
            </div>
            {consultation.status === 'complete' && consultation.advice && consultation.advice[0] ? (
                <div>
                    <p className="text-xs font-bold text-slate-400 mb-2">Response (Routed to: <span className="text-cyan-400">{consultation.routedTo}</span>):</p>
                    <StructuredAdviceCard advice={consultation.advice[0]} isMinimized />
                </div>
            ) : null}
        </div>
    );
};

const AIBoard: React.FC = () => {
    const { state } = useAppContext();
    const { forumDebates, boardConsultations } = state;

    const recentDecisions = forumDebates
        .filter(d => d.finalBoardDecision)
        .slice(0, 5);

    return (
        <div className="space-y-6">
            <h2 className="text-3xl font-bold flex items-center gap-3">
                <Users size={28} className="text-cyan-400" />
                AI Board of Directors
            </h2>

            <p className="text-slate-400 text-sm max-w-3xl">
                The AI Board provides high-level strategic oversight. It is a multi-model consensus body that reviews the most critical, high-risk signals generated by the agent swarm before they can be actioned.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <BoardMemberCard model="DeepSeek-R1" specialty="Logical Reasoning & Causal Analysis" status="online" />
                <BoardMemberCard model="Qwen-Max" specialty="Long-Context & Narrative Analysis" status="online" />
                <BoardMemberCard model="GPT-4o" specialty="Safety, Compliance & Risk Profiling" status="online" />
            </div>
            
            <DashboardCard title="Manual Board Consultations">
                <div className="space-y-4 max-h-96 overflow-y-auto">
                    {boardConsultations.length > 0 ? (
                        boardConsultations.map(c => <ManualConsultationCard key={c.id} consultation={c} />)
                    ) : (
                        <div className="text-center py-10 text-slate-500">
                            <p>No manual consultations have been initiated. Use the 'Consult AI Board' button in the Agent Command tab.</p>
                        </div>
                    )}
                </div>
            </DashboardCard>

            <DashboardCard title="Recent Board Decisions (Automated Flow)">
                 <div className="space-y-4">
                    {recentDecisions.length > 0 ? (
                        recentDecisions.map(debate => <DecisionLog key={debate.id} debate={debate} />)
                    ) : (
                        <div className="text-center py-10 text-slate-500">
                            <p>No automated board reviews have been conducted yet. Awaiting high-level signals from the Agent Forum.</p>
                        </div>
                    )}
                </div>
            </DashboardCard>
        </div>
    );
};

export default AIBoard;
