
import React, { useState, useMemo, useRef, useEffect, useCallback } from 'react';
import { TestTube, GitCommit, HelpCircle, ZoomIn, ZoomOut, Maximize } from 'lucide-react';
import { useAppContext } from '../../context/AppContext';
import { HistoricalDataPoint, RiskParityData } from '../../types';
import DashboardCard from '../DashboardCard';
import { calculateRiskParityPortfolio } from '../../services/riskParityService';
import { fetchPolygonHistoricalData } from '../../services/marketDataService';

type Timeframe = '1D' | '7D' | '30D' | '90D' | '1Y';

// --- EMA Calculation Utility ---
const calculateEMA = (data: HistoricalDataPoint[], period: number): number[] => {
    if (data.length === 0) return [];
    const k = 2 / (period + 1);
    let emaArray = [];
    // Initialize with the first value (simple approximation for visualization)
    let ema = data[0].value; 
    for (let i = 0; i < data.length; i++) {
        ema = data[i].value * k + ema * (1 - k);
        emaArray.push(ema);
    }
    return emaArray;
};

const CausalAnalysisDashboard: React.FC = () => {
    // Mock data for causal analysis
    const causalData = {
        causalAlpha: 0.12, // The "true" alpha isolated from market beta
        pathDependencyScore: 0.85, // How much the outcome depended on the specific path of events
    };

    return (
        <div className="space-y-4">
            <p className="text-sm text-slate-400">
                Analysis of "true alpha" by simulating counterfactual histories to isolate a decision's impact from market noise.
            </p>
            <div className="grid grid-cols-2 gap-4">
                <div className="bg-slate-800/50 p-4 rounded-lg">
                    <div className="text-xs text-slate-400 mb-1 flex items-center gap-1">Causal Alpha <HelpCircle size={12} title="Alpha generated by this strategy, isolated from market beta and luck, calculated across counterfactual simulations."/></div>
                    <div className="text-2xl font-bold text-green-400">+{causalData.causalAlpha}%</div>
                </div>
                <div className="bg-slate-800/50 p-4 rounded-lg">
                    <div className="text-xs text-slate-400 mb-1 flex items-center gap-1">Path Dependency <HelpCircle size={12} title="Measures how sensitive the outcome was to the precise sequence of market events. High scores indicate fragility."/></div>
                    <div className="text-2xl font-bold text-yellow-400">{causalData.pathDependencyScore.toFixed(2)}</div>
                </div>
            </div>
            <button className="w-full mt-2 py-2 px-4 bg-purple-600 hover:bg-purple-700 rounded-lg font-semibold text-sm">
                Run Pre-Mortem Simulation on Last Trade
            </button>
        </div>
    );
};

const HistoricalPriceChart: React.FC<{ data: HistoricalDataPoint[] }> = ({ data }) => {
    const svgRef = useRef<SVGSVGElement>(null);
    const [tooltip, setTooltip] = useState<{ x: number; y: number; data: HistoricalDataPoint; ema50?: number; ema14?: number } | null>(null);
    const containerRef = useRef<HTMLDivElement>(null);
    const [dimensions, setDimensions] = useState({ width: 500, height: 250 });
    
    // ViewBox state for zooming/panning
    const [viewBox, setViewBox] = useState({ x: 0, y: 0, width: 500, height: 250 });
    const isDragging = useRef(false);
    const lastPos = useRef({ x: 0, y: 0 });

    // Resize observer to handle responsive width
    useEffect(() => {
        if (!containerRef.current) return;
        const resizeObserver = new ResizeObserver(entries => {
            for (const entry of entries) {
                const { width, height } = entry.contentRect;
                setDimensions({ width, height });
                // Reset zoom on resize for simplicity, or adapt logic to maintain scale
                setViewBox({ x: 0, y: 0, width, height });
            }
        });
        resizeObserver.observe(containerRef.current);
        return () => resizeObserver.disconnect();
    }, []);

    // Calculate EMAs
    const ema50Values = useMemo(() => calculateEMA(data, 50), [data]);
    const ema14Values = useMemo(() => calculateEMA(data, 14), [data]);

    const handleWheel = (e: React.WheelEvent<SVGSVGElement>) => {
        e.preventDefault();
        if (!svgRef.current) return;

        const svg = svgRef.current;
        const pt = svg.createSVGPoint();
        pt.x = e.clientX;
        pt.y = e.clientY;
        const svgP = pt.matrixTransform(svg.getScreenCTM()?.inverse());

        // Exponential zoom
        const sensitivity = 0.001;
        const delta = Math.min(Math.max(e.deltaY, -100), 100); // Clamp delta
        const zoomScale = Math.exp(delta * sensitivity);

        let newWidth = viewBox.width * zoomScale;
        let newHeight = viewBox.height * zoomScale;

        // Constraints
        const minWidth = dimensions.width * 0.1; // Max zoom in (10%)
        const maxWidth = dimensions.width;       // Max zoom out (100%)

        if (newWidth < minWidth) {
            newWidth = minWidth;
            newHeight = dimensions.height * (minWidth / dimensions.width);
        } else if (newWidth > maxWidth) {
            newWidth = maxWidth;
            newHeight = dimensions.height;
        }

        // Zoom towards mouse pointer
        const mouseXRatio = (svgP.x - viewBox.x) / viewBox.width;
        const mouseYRatio = (svgP.y - viewBox.y) / viewBox.height;

        let newX = svgP.x - newWidth * mouseXRatio;
        let newY = svgP.y - newHeight * mouseYRatio;

        // Clamp to boundaries
        newX = Math.max(0, Math.min(newX, dimensions.width - newWidth));
        newY = Math.max(0, Math.min(newY, dimensions.height - newHeight));

        setViewBox({ x: newX, y: newY, width: newWidth, height: newHeight });
    };

    const handleMouseDown = (e: React.MouseEvent<SVGSVGElement>) => {
        isDragging.current = true;
        lastPos.current = { x: e.clientX, y: e.clientY };
        if (svgRef.current) svgRef.current.style.cursor = 'grabbing';
    };

    const handleMouseMove = (e: React.MouseEvent<SVGSVGElement>) => {
        const svg = svgRef.current;
        if (!svg) return;

        if (isDragging.current) {
            setTooltip(null);
            const dx = e.clientX - lastPos.current.x;
            const dy = e.clientY - lastPos.current.y;
            
            // Calculate movement in viewBox units
            const scaleX = viewBox.width / svg.clientWidth;
            const scaleY = viewBox.height / svg.clientHeight;
            
            let newX = viewBox.x - dx * scaleX;
            let newY = viewBox.y - dy * scaleY;
            
            // Clamp Panning
            newX = Math.max(0, Math.min(newX, dimensions.width - viewBox.width));
            newY = Math.max(0, Math.min(newY, dimensions.height - viewBox.height));

            setViewBox(prev => ({ ...prev, x: newX, y: newY }));
            lastPos.current = { x: e.clientX, y: e.clientY };
            return;
        }

        // Tooltip Logic
        if (data.length < 2) return;
        const pt = svg.createSVGPoint();
        pt.x = e.clientX;
        pt.y = e.clientY;
        const svgP = pt.matrixTransform(svg.getScreenCTM()?.inverse());
        
        const indexRatio = svgP.x / dimensions.width;
        const index = Math.max(0, Math.min(data.length - 1, Math.round(indexRatio * (data.length - 1))));

        if (index >= 0 && index < data.length) {
            const pointData = data[index];
            const values = data.map(d => d.value);
            const minVal = Math.min(...values);
            const maxVal = Math.max(...values);
            const valRange = maxVal - minVal === 0 ? 1 : maxVal - minVal;

            const xScale = (i: number) => (i / (data.length - 1)) * dimensions.width;
            const yScale = (value: number) => dimensions.height - ((value - minVal) / valRange) * dimensions.height;
            
            setTooltip({
                x: xScale(index),
                y: yScale(pointData.value),
                data: pointData,
                ema50: ema50Values[index],
                ema14: ema14Values[index]
            });
        }
    };

    const stopDragging = () => {
        isDragging.current = false;
        if (svgRef.current) svgRef.current.style.cursor = 'grab';
    };

    const handleMouseLeave = () => {
        stopDragging();
        setTooltip(null);
    };

    const resetZoom = () => {
        setViewBox({ x: 0, y: 0, width: dimensions.width, height: dimensions.height });
    };

    const { path, ema50Path, ema14Path, trendRects } = useMemo(() => {
        if (data.length < 2) return { path: '', ema50Path: '', ema14Path: '', trendRects: [] };
        const values = data.map(d => d.value);
        const minVal = Math.min(...values);
        const maxVal = Math.max(...values);
        const valRange = maxVal - minVal === 0 ? 1 : maxVal - minVal;

        const xScale = (index: number) => (index / (data.length - 1)) * dimensions.width;
        const yScale = (value: number) => dimensions.height - ((value - minVal) / valRange) * dimensions.height;

        const pathD = data.map((d, i) => `${i === 0 ? 'M' : 'L'} ${xScale(i)} ${yScale(d.value)}`).join(' ');
        const ema50PathD = ema50Values.map((v, i) => `${i === 0 ? 'M' : 'L'} ${xScale(i)} ${yScale(v)}`).join(' ');
        const ema14PathD = ema14Values.map((v, i) => `${i === 0 ? 'M' : 'L'} ${xScale(i)} ${yScale(v)}`).join(' ');
        
        const rects = [];
        for(let i=0; i < data.length - 1; i++) {
            const price = data[i].value;
            const e50 = ema50Values[i];
            const e14 = ema14Values[i];

            // Trend Confirmation Logic:
            // Uptrend: Price > EMA 50 AND EMA 14 > EMA 50
            const isConfirmedUptrend = price > e50 && e14 > e50;
            // Downtrend: Price < EMA 50 AND EMA 14 < EMA 50
            const isConfirmedDowntrend = price < e50 && e14 < e50;

            const x = xScale(i);
            const nextX = xScale(i+1);
            const w = nextX - x;

            let fill = "transparent";
            if (isConfirmedUptrend) fill = "rgba(74, 222, 128, 0.08)"; // Green tint
            else if (isConfirmedDowntrend) fill = "rgba(248, 113, 113, 0.08)"; // Red tint

            if (fill !== "transparent") {
                rects.push(
                    <rect key={i} x={x} y={0} width={w} height={dimensions.height} fill={fill} />
                )
            }
        }

        return { path: pathD, ema50Path: ema50PathD, ema14Path: ema14PathD, trendRects: rects };
    }, [data, ema50Values, ema14Values, dimensions]);

    if (data.length < 2) {
        return <div className="h-full flex items-center justify-center text-slate-500">Not enough data to display chart.</div>;
    }

    return (
        <div className="relative h-full w-full cursor-grab group" ref={containerRef} onMouseUp={stopDragging} onMouseLeave={handleMouseLeave}>
            <svg
                ref={svgRef}
                viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`}
                preserveAspectRatio="none"
                className="w-full h-full"
                onWheel={handleWheel}
                onMouseDown={handleMouseDown}
                onMouseMove={handleMouseMove}
            >
                {/* Trend Highlights (Background) */}
                <g>{trendRects}</g>

                {/* EMA 50 (Trend - Orange Dashed) */}
                <path d={ema50Path} stroke="#f97316" strokeWidth="1.5" fill="none" strokeDasharray="4,4" opacity="0.8" vectorEffect="non-scaling-stroke" />

                {/* EMA 14 (Swing - Purple) */}
                <path d={ema14Path} stroke="#a855f7" strokeWidth="1.5" fill="none" opacity="0.9" vectorEffect="non-scaling-stroke" />

                {/* Price Line (Blue) */}
                <path d={path} stroke="#22d3ee" fill="none" strokeWidth="2" vectorEffect="non-scaling-stroke" />
                
                {tooltip && (
                     <circle cx={tooltip.x} cy={tooltip.y} r="5" fill="#22d3ee" stroke="#083344" strokeWidth="2" vectorEffect="non-scaling-stroke" />
                )}
            </svg>

            {/* Hover Tooltip */}
            {tooltip && (
                <div
                    className="absolute bg-slate-950 border border-slate-700 rounded-md p-2 text-xs shadow-xl pointer-events-none z-10"
                    style={{
                        left: `${(tooltip.x - viewBox.x) / viewBox.width * 100}%`,
                        top: `${(tooltip.y - viewBox.y) / viewBox.height * 100}%`,
                        transform: `translate(-50%, -120%)`,
                    }}
                >
                    <div className="text-slate-400 mb-1">{new Date(tooltip.data.time).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</div>
                    <div className="font-bold text-slate-200">Price: ${tooltip.data.value.toFixed(2)}</div>
                    {tooltip.ema14 && <div className="text-purple-400">EMA 14: ${tooltip.ema14.toFixed(2)}</div>}
                    {tooltip.ema50 && <div className="text-orange-400">EMA 50: ${tooltip.ema50.toFixed(2)}</div>}
                </div>
            )}

            {/* Legend */}
             <div className="absolute bottom-2 left-2 flex gap-3 text-[10px] font-semibold pointer-events-none bg-slate-900/90 p-2 rounded-lg border border-slate-800 backdrop-blur-sm">
                <div className="flex items-center gap-1"><div className="w-2 h-2 bg-[#22d3ee] rounded-full"></div>Price</div>
                <div className="flex items-center gap-1"><div className="w-2 h-2 bg-[#a855f7] rounded-full"></div>EMA 14 (Swing)</div>
                <div className="flex items-center gap-1"><div className="w-2 h-2 bg-[#f97316] rounded-full"></div>EMA 50 (Trend)</div>
                <div className="flex items-center gap-1 ml-2"><div className="w-3 h-3 bg-green-400/20 border border-green-500/50 rounded-sm"></div>Confirmed Uptrend</div>
            </div>

            {/* Reset Zoom Button */}
            <button 
                onClick={resetZoom} 
                className="absolute top-2 right-2 p-1 bg-slate-800/80 text-slate-400 rounded hover:bg-slate-700 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity"
                title="Reset Zoom"
            >
                <Maximize size={14} />
            </button>
        </div>
    );
};

const CausalAnalytics: React.FC = () => {
    const { state, dispatch } = useAppContext();
    const { historicalData, dataProviders } = state;
    const [timeframe, setTimeframe] = useState<Timeframe>('90D');
    const [isLoading, setIsLoading] = useState(false);

    const timeframes: { label: Timeframe, days: number }[] = [
        { label: '1D', days: 1 },
        { label: '7D', days: 7 },
        { label: '30D', days: 30 },
        { label: '90D', days: 90 },
        { label: '1Y', days: 365 },
    ];

    const handleTimeframeChange = useCallback(async (newTimeframe: Timeframe, days: number) => {
        setTimeframe(newTimeframe);
        setIsLoading(true);
        try {
            const newData = await fetchPolygonHistoricalData('AAPL', days, dataProviders);
            dispatch({ type: 'SET_HISTORICAL_DATA', payload: newData });
        } catch (error) {
            console.error("Failed to fetch new timeframe data:", error);
            dispatch({ type: 'SHOW_NOTIFICATION', payload: { type: 'error', message: 'Failed to load chart data for timeframe.' }});
        } finally {
            setIsLoading(false);
        }
    }, [dispatch, dataProviders]);

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h2 className="text-3xl font-bold flex items-center gap-3"><TestTube size={28} className="text-cyan-400"/> Causal Analytics</h2>
                <span className="text-sm font-semibold text-slate-400">Primary Symbol: AAPL</span>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-slate-900 rounded-lg p-4 border border-slate-800">
                    <div className="text-slate-400 text-sm mb-2">Sharpe Ratio</div>
                    <div className="text-2xl font-bold text-green-400">1.82</div>
                </div>
                <div className="bg-slate-900 rounded-lg p-4 border border-slate-800">
                    <div className="text-slate-400 text-sm mb-2">Max Drawdown</div>
                    <div className="text-2xl font-bold text-red-400">-12.5%</div>
                </div>
                <div className="bg-slate-900 rounded-lg p-4 border border-slate-800">
                    <div className="text-slate-400 text-sm mb-2">Profit Factor</div>
                    <div className="text-2xl font-bold text-blue-400">2.27</div>
                </div>
                <div className="bg-slate-900 rounded-lg p-4 border border-slate-800">
                    <div className="text-slate-400 text-sm mb-2">Total Trades</div>
                    <div className="text-2xl font-bold text-purple-400">142</div>
                </div>
            </div>
            
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
                <div className="lg:col-span-3">
                    <DashboardCard title="Historical Price (AAPL) & EMA Trend">
                        <div className="flex justify-end gap-1 mb-2">
                            {timeframes.map(tf => (
                                <button key={tf.label} onClick={() => handleTimeframeChange(tf.label, tf.days)}
                                    className={`px-3 py-1 text-xs font-semibold rounded-md ${timeframe === tf.label ? 'bg-cyan-500/30 text-cyan-300' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'}`}>
                                    {tf.label}
                                </button>
                            ))}
                        </div>
                        <div className="h-80">
                        {(isLoading) ? (
                            <div className="flex items-center justify-center h-full text-slate-500">Loading historical data...</div>
                        ) : (
                            <HistoricalPriceChart data={historicalData} />
                        )}
                        </div>
                    </DashboardCard>
                </div>
                <div className="lg:col-span-2">
                    <DashboardCard title="Causal Inference Engine">
                        <CausalAnalysisDashboard />
                    </DashboardCard>
                </div>
            </div>

        </div>
    );
};

export default CausalAnalytics;
