
export const XAUUSD_SWING_STRATEGY_CODE = `//+------------------------------------------------------------------+
//|                                  XAUUSD_Advanced_Hybrid_System.mq5|
//|                        Generated by VORTIGEN AI                  |
//+------------------------------------------------------------------+
#property copyright "VORTIGEN AI"
#property version   "3.80"
#property strict

#include <Trade\\Trade.mqh>

//--- Input parameters
input double   InpLotSize        = 0.01;     // Lot Size
input int      InpMagicNum       = 812100;   // Magic Number
input double   InpRRRatio        = 2.0;      // Risk:Reward Ratio

//--- Moving Averages (EMA)
input int      InpEMAFast        = 8;        // Fast EMA (Momentum)
input int      InpEMASlow        = 12;       // Slow EMA (Confirmation)
input int      InpEMATrend       = 100;      // Trend EMA (Anchor)

//--- Advanced Filters
input int      InpRSI_Period     = 14;       // RSI Period (Momentum)
input int      InpHMAPeriod      = 9;        // Hull MA Period (Trend Filter)
input int      InpALMAPeriod     = 5;        // ALMA Period (Smoothing)

//--- Risk Management
input bool     InpUseATR         = true;     // Use ATR for Stop Loss?
input int      InpATRPeriod      = 14;       // ATR Period
input double   InpATRMultiplier  = 1.5;      // ATR Multiplier for SL
input int      InpSLPoints       = 400;      // Fixed SL Points (Fallback/Alternative)

//--- Global variables
int            hFast, hSlow, hTrend, hRSI, hATR, hHMA, hALMA;
CTrade         trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNum);

   //--- Standard Indicators
   hFast = iMA(_Symbol, _Period, InpEMAFast, 0, MODE_EMA, PRICE_CLOSE);
   hSlow = iMA(_Symbol, _Period, InpEMASlow, 0, MODE_EMA, PRICE_CLOSE);
   hTrend = iMA(_Symbol, _Period, InpEMATrend, 0, MODE_EMA, PRICE_CLOSE);
   hRSI = iRSI(_Symbol, _Period, InpRSI_Period, PRICE_CLOSE);
   
   // Always init ATR handle if period > 0, just in case user toggles it on later
   if(InpATRPeriod > 0) {
      hATR = iATR(_Symbol, _Period, InpATRPeriod);
   } else {
      hATR = INVALID_HANDLE;
   }

   if(hFast == INVALID_HANDLE || hSlow == INVALID_HANDLE || hTrend == INVALID_HANDLE || hRSI == INVALID_HANDLE)
     {
      Print("CRITICAL: Failed to create core indicator handles. Error: ", GetLastError());
      return(INIT_FAILED);
     }

   //--- Custom Indicators (HMA & ALMA)
   // Note: These rely on external .ex5 files being present in the registry.
   hHMA = iCustom(_Symbol, _Period, "Hull Moving Average", InpHMAPeriod);
   hALMA = iCustom(_Symbol, _Period, "ALMA", InpALMAPeriod, 0, 0.85, 6); 

   if(hHMA == INVALID_HANDLE) Print("WARNING: HMA Indicator not found. Filter disabled.");
   if(hALMA == INVALID_HANDLE) Print("WARNING: ALMA Indicator not found. Filter disabled.");

   Print("Init Success. Strategy: EMA(", InpEMAFast, "/", InpEMASlow, "/", InpEMATrend, ") + HMA(", InpHMAPeriod, ") + ALMA(", InpALMAPeriod, ") + RSI(", InpRSI_Period, ")");
   if(InpUseATR) Print("Risk Management: Dynamic ATR (", InpATRMultiplier, "x)");
   else Print("Risk Management: Fixed Points (", InpSLPoints, ")");
   
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Robust Error Checks
   if(!TerminalInfoInteger(TERMINAL_CONNECTED)) return;
   if(!MQLInfoInteger(MQL_TRADE_ALLOWED)) return;

   //--- Buffers
   double bFast[], bSlow[], bTrend[], bRSI[], bATR[], bHMA[], bALMA[];
   ArraySetAsSeries(bFast, true); ArraySetAsSeries(bSlow, true); ArraySetAsSeries(bTrend, true);
   ArraySetAsSeries(bRSI, true); ArraySetAsSeries(bATR, true); ArraySetAsSeries(bHMA, true); ArraySetAsSeries(bALMA, true);

   //--- Data Copy & Validation
   if(CopyBuffer(hFast, 0, 0, 3, bFast) < 3 || CopyBuffer(hSlow, 0, 0, 3, bSlow) < 3 ||
      CopyBuffer(hTrend, 0, 0, 3, bTrend) < 3 || CopyBuffer(hRSI, 0, 0, 3, bRSI) < 3)
     {
      Print("WARNING: Insufficient standard data.");
      return;
     }
     
   //--- ATR Data Logic
   // If InpUseATR is true, we MUST have ATR data. If fail, fallback to fixed points safely.
   bool useATR = InpUseATR;
   if(useATR) {
      if(hATR == INVALID_HANDLE || CopyBuffer(hATR, 0, 0, 3, bATR) < 3) {
          Print("WARNING: ATR data unavailable. Falling back to Fixed Points.");
          useATR = false;
      }
   }

   //--- Custom Indicator Data
   bool useHMA = (hHMA != INVALID_HANDLE);
   bool useALMA = (hALMA != INVALID_HANDLE);
   double hmaVal = 0, almaVal = 0;

   if(useHMA && CopyBuffer(hHMA, 0, 0, 2, bHMA) < 2) { Print("Wait for HMA"); return; }
   if(useHMA) hmaVal = bHMA[1];

   if(useALMA && CopyBuffer(hALMA, 0, 0, 2, bALMA) < 2) { Print("Wait for ALMA"); return; }
   if(useALMA) almaVal = bALMA[1];

   //--- Values
   double fastNow = bFast[1], fastPrev = bFast[2];
   double slowNow = bSlow[1], slowPrev = bSlow[2];
   double trendVal = bTrend[1];
   double rsiVal = bRSI[1];
   double closePrice = iClose(_Symbol, _Period, 1);

   //--- Signals
   bool crossUp = (fastPrev <= slowPrev) && (fastNow > slowNow);
   bool crossDown = (fastPrev >= slowPrev) && (fastNow < slowNow);
   
   //--- Strict Trend Logic: All EMAs aligned
   bool trendBullish = (closePrice > trendVal) && (fastNow > trendVal) && (slowNow > trendVal);
   bool trendBearish = (closePrice < trendVal) && (fastNow < trendVal) && (slowNow < trendVal);

   //--- Smoothing Filters
   bool hmaBullish = useHMA ? (closePrice > hmaVal) : true;
   bool hmaBearish = useHMA ? (closePrice < hmaVal) : true;
   
   bool almaBullish = useALMA ? (closePrice > almaVal) : true;
   bool almaBearish = useALMA ? (closePrice < almaVal) : true;

   //--- ENTRY & RISK MANAGEMENT LOGIC
   double slDist = 0;
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   
   if(useATR) {
      slDist = bATR[1] * InpATRMultiplier;
   } else {
      slDist = InpSLPoints * point;
   }

   //--- LONG ENTRY
   // 1. EMA Crossover (8 > 12)
   // 2. Strict Trend (Price, 8, 12 > 100)
   // 3. HMA & ALMA Confirmation
   // 4. RSI > 50
   if(crossUp && trendBullish && hmaBullish && almaBullish && rsiVal > 50)
     {
      if(!PositionSelect(_Symbol)) 
        {
         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double slPrice = NormalizeDouble(ask - slDist, _Digits);
         double tpPrice = NormalizeDouble(ask + (slDist * InpRRRatio), _Digits);

         string riskMode = useATR ? "ATR" : "Fixed";
         Print("SIGNAL LONG | Price:", ask, " | Mode:", riskMode, " | SL:", slPrice);
         
         if(trade.Buy(InpLotSize, _Symbol, ask, slPrice, tpPrice, "Hybrid EMA Strict Buy"))
            Print("BUY Ticket:", trade.ResultOrder());
         else
            Print("BUY Failed:", trade.ResultRetcodeDescription());
        }
     }

   //--- SHORT ENTRY
   // 1. EMA Crossover (8 < 12)
   // 2. Strict Trend (Price, 8, 12 < 100)
   // 3. HMA & ALMA Confirmation
   // 4. RSI < 50
   if(crossDown && trendBearish && hmaBearish && almaBearish && rsiVal < 50)
     {
      if(!PositionSelect(_Symbol)) 
        {
         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
         double slPrice = NormalizeDouble(bid + slDist, _Digits);
         double tpPrice = NormalizeDouble(bid - (slDist * InpRRRatio), _Digits);

         string riskMode = useATR ? "ATR" : "Fixed";
         Print("SIGNAL SHORT | Price:", bid, " | Mode:", riskMode, " | SL:", slPrice);
         
         if(trade.Sell(InpLotSize, _Symbol, bid, slPrice, tpPrice, "Hybrid EMA Strict Sell"))
            Print("SELL Ticket:", trade.ResultOrder());
         else
            Print("SELL Failed:", trade.ResultRetcodeDescription());
        }
     }
  }
`;
